version: '3'
services:
    web:
        build:
            context: . # This directory
            dockerfile: Dockerfile.dev

        ports:
            - "3000:3000"
        volumes:
            - /home/node/app/node_modules
            - .:/home/node/app # Map current directory to app
